Feat  skip to content
sparkbox/team-availability pull request #13
Opened 2022-04-28 14:23 UTC by theogainey

### Description
This PR adds a SkipToContent component, a visually hidden mixin, and base styles to SkipToContent component so that it is  visually hidden but appears on focus. 

### Spec

See Story: [FSA22V1-171]((https://sparkbox.atlassian.net/browse/FSA22V1-171))

### Validation

* [ ] This PR has code changes, and our linters still pass.
* [ ] This PR affects production code, so it was browser tested (see below).
* [ ] Changes are browser tested. This includes functionality, accessibility, responsiveness, and design.

#### To Validate

1. Make sure all PR Checks have passed (GitHub Actions, CircleCI, Code Climate, Snyk, etc).
2. Pull down all related branches.
3. Confirm all tests pass.
4. Open preview deploy and confirm that SkipToContent component is initially visually hidden, can be navigated to with the tab key, appears when in focus, and switches focus when clicked

2022-04-28 14:26 UTC, theogainey commented on pages/index.jsx
> +  const skipOnClick = () => contentRef.current.focus();
I am wondering if using `useRef` and the DOM method `.focus()` is necessary. I was having trouble getting focus to switch without it but I also initially had a setting turned on in my browser that affected tabbing through a page.

2022-04-28 18:55 UTC, dustin-jw requested changes
Sometimes when all you have is a hammer (React), every problem looks like a nail (a use case for `useRef`) 😂 

This can be simplified a bit, and extended to other pages, but you've got the basics in place.

2022-04-28 21:10 UTC, dustin-jw requested changes
Changes look good! I just noticed a few CSS things that we can clean up before merging.

2022-04-28 21:10 UTC, dustin-jw commented on styles/globals.scss
> +}
This probably got obliterated in conflict resolution, but these styles were removed in an earlier PR, so we should get rid of them here, too.

2022-04-28 21:10 UTC, dustin-jw commented on styles/globals.scss
> +}
Lets move this to `styles/components/_skip-to-content.scss` and then import that file here. Ideally, the entry point should be composed entirely of `@import` statements.

I'd like to see the class name namespaced as well, like `.cmp-skip-to-content` ('cmp' for component).

2022-04-29 13:48 UTC, theogainey commented
At the risk of getting ahead of myself I am going to go ahead and ask @arnest00 to come in and give it the second review.

2022-04-29 13:50 UTC, dustin-jw approved these changes

2022-04-29 14:03 UTC, arnest00 commented on styles/globals.scss
> +// Introduction
Thanks for getting this file organized like this!

2022-04-29 14:09 UTC, merged