feat: Refine gradient styling and hover
sparkbox/team-availability pull request #52
Opened 2022-06-22 22:11 UTC by arnest00

### Description
- TradingCardImage true to design

### Spec
Designs: [Designs](https://www.figma.com/file/kswpPSHH2h5njVyfGDbIHk/FSA-Capstone-Project-2022)
See Story: [259](https://sparkbox.atlassian.net/browse/FSA22V1-259)

### Validation
* [ ] This PR has visual elements, so it was reviewed by a designer.
* [ ] This PR has code changes, and our linters still pass.
* [ ] This PR affects production code, so it was browser tested (see below).
* [ ] Changes are browser tested. This includes functionality, accessibility, responsiveness, and design.

#### To Validate

1. Make sure all PR Checks have passed.
2. Pull down `feat--refine-gradient-styling` branch.
3. Run `npm i`.
4. Confirm all linters pass.
5. Confirm all tests pass.
6. Open deploy preview and verify base and hover state match Figma design.

2022-06-24 13:23 UTC, empee3 approved these changes
![Thumbs up](https://media.giphy.com/media/3o7abGQa0aRJUurpII/giphy.gif)

2022-06-28 17:10 UTC, theogainey requested changes
Great job fixing that ugly hover state bug! There is one more bug though if you compare the two screenshots, one from the preview deploy & the other from the main deploy, you'll see that now on mobile some of the images have a white strip along part of their edges. My guess is that the change from `::after` to `::before` pseudo-elements may have something to do with it. 
![IMG_0605](https://user-images.githubusercontent.com/32309792/176241523-9b25766b-f9e5-4e66-9075-deb39894fa13.PNG)
![IMG_0607](https://user-images.githubusercontent.com/32309792/176241527-4b723fe1-9df0-475a-8dce-f6f09c2ec84e.PNG)

2022-06-28 19:39 UTC, theogainey approved these changes

2022-06-28 19:39 UTC, theogainey commented
![](https://i.imgflip.com/2d2gjb.jpg)

2022-06-28 19:40 UTC, merged